#!/usr/bin/env python

from sisa.puco import PUCO
from sisa.settings import USER_SISA, PASS_SISA
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("--dni", type=str, help="DNI del Ciudadano")
parser.add_argument("--user", type=str, help="Usario SISA válido")
parser.add_argument("--password", type=str, help="Clave SISA válida")

args = parser.parse_args()

USER_SISA = args.user
PASS_SISA = args.password
puco = PUCO(dni=args.dni)
print(puco.get_info_ciudadano())
