#!/usr/bin/env python
from __future__ import print_function
from sisa.apis.puco import Puco
from sisa.apis import settings
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("--dni", type=str, help="DNI del Ciudadano")
parser.add_argument("--user", type=str, help="Usario SISA válido")
parser.add_argument("--password", type=str, help="Clave SISA válida")

args = parser.parse_args()

settings.USER_SISA = args.user
settings.PASS_SISA = args.password
puco = Puco(dni=args.dni)
print(puco.get_info_ciudadano())
